### ISSUE TITLE
Bekreftelse på utsendt nyhetsbrev

### ISSUE THREAD

**Issue by weblady** [webrtd/website#101]
Landssekretær Therese har fått sendt ut nyhetsbrev uten vedlegg til ledere og sekretærer og til alle distriktene. og fikk bekreftet fra egen klubb sekretær at den var mottatt. Men intron viste ingen bekreftelse på at den ble sendt til alle. Det ønsker hun å ha, en bekreftelse på hvor mange den er sendt til.

**Comment by webrtd** [comment]
Det gør systemet allerede. Når man udsender skriver den "Nyhetsbrevet er blitt sendt til %%count%% mottakere." Hvor %%count%% bliver erstattet af det faktiske antal.
