### ISSUE TITLE
Sms bug

### ISSUE THREAD

**Issue by webmasterRTN** [webrtd/website#103]
Sms funker ikke

**Comment by webrtd** [comment]
Fejlbeskrivelse?

**Comment by webrtd** [comment]
Sidste SMS der er registreret i systemet er afsendt 2015-02-27 14:21:48

**Comment by webmasterRTN** [comment]
Mottakere mottar ikke sms 

Sendt fra min iPhone

**Comment by webmasterRTN** [comment]
Vet det ble sendt fra klubben i Holmestrand i går og en test sms i dag

Sendt fra min iPhone

**Comment by webrtd** [comment]
Hvad var teksten?



—
Rasmus Kaae
Mobil: +45 28720413

**Comment by webmasterRTN** [comment]
Den som ble sendt i dag var noe i retning: Morgenhilsen fra klubbformann

 

Fra: webrtd [mailto:notifications@github.com] 
Sendt: 4. mars 2015 20:55
Til: webrtd/website
Kopi: webmasterRTN
Emne: Re: [website] Sms bug (#103)

 

Hvad var teksten?



—
Rasmus Kaae
Mobil: +45 28720413

**Comment by webrtd** [comment]
Not a bug
