### ISSUE TITLE
Avsenderadresse på nyhetsbrev

### ISSUE THREAD

**Issue by weblady** [webrtd/website#129]
Når nyhetsbrev sendes ut fra president, så står den som sendt fra avsenderadresse LF@lcnorge.no. Dette er ikke ei adresse som vi benytter, presidentens epostadresse er president@lcnorge.no, så det må være denne som står som avsenderadresse. Dette må fikses. Hvilke avsenderadresser står det når det sendes nyhetbrev fra de andre vervene? Det må vel fikses for alle verv da tipper jeg?

**Comment by francisrath** [comment]
Er dette fortsatt feil? Jeg tror jeg kan få fikset det.

**Comment by weblady** [comment]
Hei Francis,

Dette er fortsatt feil ja, så det er supert om du vil se på det og
muligens får fikset det! :) Jeg pleier å få alle autoreplys i tillegg til
at medlemmer sender mailer til meg når de ikke kan delta på møter, for de
følger ikke med på hva som står som avsenderadresse ;)

Silje

Den tor, juni 30, 2016, 15:07 skrev Francis Rath:

> Er dette fortsatt feil? Jeg tror jeg kan få fikset det.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/webrtd/website/issues/129#issuecomment-229652402

Med vennlig hilsen

Silje Salte Tidemandsen
Weblady 2014/16
Ladies Circle Norway

**Comment by francisrath** [comment]
Denne skal være fikset, men får ikke lukket issue. Kan du lukke @webrtd  :)

**Comment by weblady** [comment]
Takk Francis. Jeg lukker den.:-)
