### ISSUE TITLE
Automatisk påminnelse til klubbmøter

### ISSUE THREAD

**Issue by weblady** [webrtd/website#54]
Er det mulig å få automatiske påminnelser for klubbmøtene? I den gamle intron så kunne man sette feks. 7 dagers påminnelse. Da gikk det automatisk ut en mail til medlemmene. Det er et stort ønske om dette!
Eller må sekretær i klubben sende ut en ny møteinnkalling ca en uke før.

**Comment by webrtd** [comment]
RTN / LCN sekretær ønske #70
