### ISSUE TITLE
RTN /LCN / RTD - sms tjeneste

### ISSUE THREAD

**Issue by webmasterRTN** [webrtd/website#57]
Hva er status og kostnader rundt sms tjenesten?
STOR etterspørsel etter denne tjenesten i Norge.

**Comment by webmasterRTN** [comment]
etter oppstart av SMS funksjon:
Kan du lage samme funksjon på "send beskjed til klubbens bestyrelse" (og endre fra estyrelse til Styre)
I tillegg trengs funksjonen: vedlegg (som på send ut referat; 3 mulige vedlegg)

**Comment by webrtd** [comment]
?

—
Rasmus Kaae
Mobil: +45 28720413

**Comment by webmasterRTN** [comment]
Hva forsto du ikke?
Lage mulighet for SMS til bestyrelsen?
Da vil vi enkelt også kunne sende Mail via intron til styret uten å ha installert tredjeparts programmer som feks outlook. (Tidligere etterspurt)
Bestyrelse heter på norsk: Styret
Når vi sender ut referat fra møtene kan vi legge ved inntil 3 vedlegg. Det er ønsket når vi sender melding (ikke sms) til klubbens medlemmer også

Sendt fra min iPhone
