### ISSUE TITLE
Nytt medlem

### ISSUE THREAD

**Issue by weblady** [webrtd/website#89]
Når man legger til et nytt medlem, så blir dette medlemmet automatisk påmeldt fremtidige møter, og styret (kun sekretær?) mail om at det nye medlemmet er påmeldt møtene uten at medlemmet har gått inn og meldt seg på møtet. Ønsker å fjerne denne automatiske påmeldingen og mailen til styret.  Tidspunktet for opprettelsen av medlemmet står som svartidspunktet på påmeldingen på møtet. Alle medlemmer blir jo påmeldt automatisk når møter blir opprettet, men da uten at det går ut noen mail til styret om det.

**Comment by webrtd** [comment]
Work as designed :)
