### ISSUE TITLE
Send beskjed på profilsiden

### ISSUE THREAD

**Issue by weblady** [webrtd/website#90]
Therese testet å sende beskjed til meg på min profilside. Avsender fra denne mailen sto som LS@lcnorge.no som er ei mailadresse som vi ikke benytter, vi har secretary@lcnorge.no på vår landssekretær. Avsender i mailen sto også som RoundTable og må endres til LadiesCircle.

**Comment by webrtd** [comment]
Systemet sender fra <shortname>@lcnorge.no. Har ændret shortname til SECRETARY i databasen. Sig til hvis det giver problemer.
