### ISSUE TITLE
RTN / LCN glemt passord

### ISSUE THREAD

**Issue by webmasterRTN** [webrtd/website#94]
Informasjon når medlemmer trykker glemt passord: Sjekk søppelpost om du ikke mottar nytt passord innen 6 minutter

**Comment by webrtd** [comment]
Blev vi ikke enige om at det var kommunikation LCN/RTN skulle distribuere?

**Comment by webmasterRTN** [comment]
Blir fort for mye informasjon direkte fra RTN/LCN slik at medlemmene ikke får det med seg. Er det mye arbeid å få det inn i teksten som kommer når de trykker "Glemt Passord"?
